on: [push]

name: "CI"

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [7.4, 8.0, 8.1, 8.2]
        # laravel-versions: [8.*, 8.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: intl, gd, zip, pdo, sqlite, pdo_sqlite, dom, curl, libxml, mbstring, fileinfo, exif, iconv
          ini-values: memory_limit=-1,disable_functions="",pcov.exclude="~(vendor|tests|node_modules)~",pcov.directory="./"
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Composer Install
        run: composer install

      - name: PHP/Composer Vendor Size
        run: |
          echo SCORE=`du -sm vendor/ | awk '{print $1}'` >> "$GITHUB_ENV"

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: php-vendor-size

      - name: PHPUNIT Tests
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Code Coverage
        run: |
          curl -sLk https://raw.githubusercontent.com/kevincobain2000/cover-totalizer/master/install.sh | sh
          echo SCORE=`./cover-totalizer coverage.xml` >> "$GITHUB_ENV"

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: coverage

      - uses: kevincobain2000/action-coveritup@v1
        with:
          pr_comment: true



